-- ==========================================
-- ส่วนที่ 1: โครงสร้างตารางของคุณ (ปรับปรุง Default Time)
-- ==========================================

CREATE TABLE IF NOT EXISTS temperature_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reading_date DATE NOT NULL DEFAULT (NOW() AT TIME ZONE 'Asia/Bangkok')::DATE, -- เติม Default เวลาไทย
  reading_time TIME NOT NULL DEFAULT (NOW() AT TIME ZONE 'Asia/Bangkok')::TIME, -- เติม Default เวลาไทย
  temperature NUMERIC(6,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_temperature_created_at
  ON temperature_readings (created_at);


CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  temperature NUMERIC(6,2) NOT NULL,
  threshold NUMERIC(6,2) NOT NULL,
  line_sent BOOLEAN NOT NULL DEFAULT FALSE,
  message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_created_at
  ON alerts (created_at);


CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY,
  danger_threshold NUMERIC(6,2) NOT NULL DEFAULT 100,
  reset_threshold NUMERIC(6,2) NOT NULL DEFAULT 100,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO settings (id, danger_threshold, reset_threshold)
VALUES (1, 100, 100)
ON CONFLICT (id) DO NOTHING;


CREATE TABLE IF NOT EXISTS device_status (
  id INTEGER PRIMARY KEY,
  device_name VARCHAR(100) NOT NULL,
  wifi_status BOOLEAN DEFAULT FALSE,
  sensor_status BOOLEAN DEFAULT FALSE,
  battery_percent NUMERIC(5,2),
  last_seen TIMESTAMPTZ
);

INSERT INTO device_status (id, device_name)
VALUES (1, 'เครื่องตรวจจับความร้อน #01')
ON CONFLICT (id) DO UPDATE SET device_name = EXCLUDED.device_name;


-- ==========================================
-- ส่วนที่ 2: ตั้งค่าความปลอดภัย (RLS) อนุญาตให้ฮาร์ดแวร์ส่งข้อมูลได้
-- ==========================================

ALTER TABLE temperature_readings ENABLE ROW LEVEL SECURITY;

-- อนุญาตให้อุปกรณ์ที่ใช้ anon_key สามารถเพิ่มข้อมูลได้
CREATE POLICY "Allow hardware to insert temperature"
ON temperature_readings
FOR INSERT
TO anon
WITH CHECK (true);

-- อนุญาตให้อ่านข้อมูลไปแสดงผลบน Dashboard ได้
CREATE POLICY "Allow public read access"
ON temperature_readings
FOR SELECT
TO anon
USING (true);

-- ==========================================
-- ส่วนที่ 3 (ทางเลือก): โค้ดสร้างข้อมูลจำลองของคุณ (รันครั้งเดียว)
-- ==========================================
-- หากคุณต้องการข้อมูลจำลอง 30 วัน ไว้ทดสอบกราฟ ให้ไฮไลต์โค้ดส่วนนี้แล้วกดรัน
/*
INSERT INTO temperature_readings (reading_date, reading_time, temperature, created_at)
SELECT
  (t AT TIME ZONE 'Asia/Bangkok')::DATE,
  (t AT TIME ZONE 'Asia/Bangkok')::TIME,
  ROUND((CASE
    WHEN EXTRACT(HOUR FROM (t AT TIME ZONE 'Asia/Bangkok')) BETWEEN 13 AND 14
         AND MOD(EXTRACT(DAY FROM (t AT TIME ZONE 'Asia/Bangkok'))::INT, 5) = 0
      THEN 101 + RANDOM() * 10
    ELSE 30 + RANDOM() * 25
  END)::NUMERIC, 2),
  t
FROM generate_series(
  NOW() - INTERVAL '30 days', NOW(), INTERVAL '3 minutes'
) AS t;
*/