-- Supabase / PostgreSQL
-- ตั้ง Time Zone เป็นประเทศไทยในการแสดงผลของ SQL Editor ได้ด้วย:
-- SET TIME ZONE 'Asia/Bangkok';

CREATE TABLE IF NOT EXISTS temperature_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reading_date DATE NOT NULL,
  reading_time TIME NOT NULL,
  temperature NUMERIC(6,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_temperature_created_at
  ON temperature_readings (created_at);

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  temperature NUMERIC(6,2) NOT NULL,
  threshold NUMERIC(6,2) NOT NULL,
  line_sent BOOLEAN NOT NULL DEFAULT FALSE,
  message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_created_at
  ON alerts (created_at);

CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY,
  danger_threshold NUMERIC(6,2) NOT NULL DEFAULT 100,
  reset_threshold NUMERIC(6,2) NOT NULL DEFAULT 100,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO settings (id, danger_threshold, reset_threshold)
VALUES (1, 100, 100)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS device_status (
  id INTEGER PRIMARY KEY,
  device_name VARCHAR(100) NOT NULL,
  wifi_status BOOLEAN DEFAULT FALSE,
  sensor_status BOOLEAN DEFAULT FALSE,
  battery_percent NUMERIC(5,2),
  last_seen TIMESTAMPTZ
);

INSERT INTO device_status (id, device_name)
VALUES (1, 'เครื่องตรวจจับความร้อน #01')
ON CONFLICT (id) DO UPDATE SET device_name = EXCLUDED.device_name;

-- ตัวอย่างข้อมูล 30 วัน ทุก 3 นาที (ประมาณ 14,401 แถว)
-- รันส่วนนี้ครั้งเดียวถ้าต้องการข้อมูลทดสอบกราฟ
INSERT INTO temperature_readings (reading_date, reading_time, temperature, created_at)
SELECT
  (t AT TIME ZONE 'Asia/Bangkok')::DATE,
  (t AT TIME ZONE 'Asia/Bangkok')::TIME,
  ROUND((CASE
    WHEN EXTRACT(HOUR FROM (t AT TIME ZONE 'Asia/Bangkok')) BETWEEN 13 AND 14
         AND MOD(EXTRACT(DAY FROM (t AT TIME ZONE 'Asia/Bangkok'))::INT, 5) = 0
      THEN 101 + RANDOM() * 10
    ELSE 30 + RANDOM() * 25
  END)::NUMERIC, 2),
  t
FROM generate_series(
  NOW() - INTERVAL '30 days', NOW(), INTERVAL '3 minutes'
) AS t;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user'
    CHECK (role IN ('user', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_username
  ON users (username);