CREATE TABLE IF NOT EXISTS telegram_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id BIGINT NOT NULL UNIQUE,
  first_name TEXT,
  username TEXT,
  chat_type TEXT NOT NULL DEFAULT 'private',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_telegram_subscribers_active
  ON telegram_subscribers (is_active);

CREATE INDEX IF NOT EXISTS idx_telegram_subscribers_last_seen
  ON telegram_subscribers (last_seen_at);
